### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by lolminerxmrig** [fyx1t/ssh-brute#1]
Hi.
Error : 

![image](https://github.com/fyx1t/ssh-brute/assets/108659226/71fcc8b5-3775-413e-8b7a-f8a005e08d41)

**Comment by fyx1t** [comment]
Hi, @lolminerxmrig! Thanks for your feedback!

This script has a match/case construct, which appeared in Python 3.10 and is described in PEP 622 (https://peps.python.org/pep-0622/). Thus, you need to have Python version 3.10 or higher to run this script.
However, I will soon be making a few fixes to the script, namely:
1. Clarify the requirements for the script to work properly
2. Replace the match/case construct with if/else to work on past versions of Python.

Thanks again for the issue and good luck!
